language: c++
sudo: false


addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    - chef-current-precise

    packages:
    - cmake
    - time
    - pkg-config
    - g++-4.8

cache:
  directories:
  - $HOME/ibex
  #- $HOME/boost_1_58_0
  - $HOME/Downloads

# matrix:
  # include:

os: osx
compiler: clang

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install python3; fi
  - echo $(python3 -V)
install:
  - bash ./travis_script/build_Ibex4pyIbex.sh
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex
#  - pip install vibes
# compiler:
#   - gcc-4.8
# os:
#   #- linux
#   - osx

# before_install:
#   - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install python3; fi

# before_script:
#   - bash ./travis_script/build_Ibex4pyIbex.sh
#   - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex
#   - pip install vibes
# # command to run tests
script:  
  - mkdir build
  - cd build
  - export version=$(python3 -c "import sys; print(sys.version[:3])")
  - echo $version
  - ls ${HOME}/ibex
  - ls ${HOME}/ibex/lib
  - cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DIBEX_ROOT=${HOME}/ibex -DPYTHON_VERSION=${version} ../
  - make && make install
  - export PYTHONPATH=$PYTHONPATH:/home/travis/lib/python${version}/site-packages
  - python -c "from pyIbex import *"
  - make test